### ISSUE TITLE
Does Xamarin support WorkManager now?

### ISSUE THREAD

**Issue by jom16antonio** [xamarin/AndroidSupportComponents#152] opened 2019-02-14 04:22 UTC
This is just a quick inquiry. How do I use WorkManager with Xamarin?
Is this something being worked on?

> VS bug [#805952](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/805952)

**Comment by moljac** [comment] 2019-02-20 12:59
Yes. I finished the bindings and am working on nuget package. I hope it will be released soon.

**Comment by Redth** [comment] 2019-03-01 02:14
WorkManager is still in preview from Google.  We are working on bindings for it in the meantime.

**Comment by jom16antonio** [comment] 2019-03-01 03:18
Theres a rc01 (release candidate) hope we could test your bindings with that version.

**Comment by chrisreps** [comment] 2019-03-06 08:29
Any update on WorkManager support, now that Android have pushed a stable release, identical to the release candidate, on the 5th of March?

**Comment by Redth** [comment] 2019-03-15 04:14
https://www.nuget.org/packages/Xamarin.Android.Arch.Work.Runtime

Just published, should work for you now :)

**Closed by Redth** 2019-03-15 04:14 UTC
Labels: azdo-sync

**Comment by sdobart** [comment] 2019-03-25 19:52
I added that NuGet package to my project, but I don't appear to have any access to the Xamarin.Android.Arch namespace?

**Comment by elisabeth-mitton** [comment] 2019-05-10 15:38
@sdobart How did you do? I cannot find the `Worker` class, can you help please?

**Comment by sdobart** [comment] 2019-05-10 17:23
@elisabeth-mitton You need to change your Android project's target SDK to version 28 (9.0 Pie), and then install the NuGet Package "Xamarin.Android.Arch.Work.Runtime".

**Comment by vnwonah** [comment] 2019-06-04 12:14
I am targeting SDK 28 and have the nuget installed yet getting `the type or namespace AndroidX could not be found.`  Any help please? @moljac

**Comment by jalbertSyncroTech** [comment] 2019-06-12 16:02
Can anyone comment if the Xamarin WorkManager bindings support "ListenableWorker"?

I know it supports "Worker", but that requires that all of the work be done synchronously. In order to do any asynchronous work the worker needs to sub-class "ListenableWorker" directly.

The "ListenableWorker" is supposed to have an abstract "startWork()" function, but I'm not seeing it in the class definition from the "Xamarin.Android.Arch.Work.Runtime" NuGet package.
https://developer.android.com/reference/androidx/work/ListenableWorker.html#startWork()

**Comment by SteveFarmerJr** [comment] 2019-07-11 13:28
> Can anyone comment if the Xamarin WorkManager bindings support "ListenableWorker"?
> 
> I know it supports "Worker", but that requires that all of the work be done synchronously. In order to do any asynchronous work the worker needs to sub-class "ListenableWorker" directly.
> 
> The "ListenableWorker" is supposed to have an abstract "startWork()" function, but I'm not seeing it in the class definition from the "Xamarin.Android.Arch.Work.Runtime" NuGet package.
> https://developer.android.com/reference/androidx/work/ListenableWorker.html#startWork()

I was under the impression that Xamarin WorkManager's "Worker" was asynchronous.
https://devblogs.microsoft.com/xamarin/getting-started-workmanager/

**Comment by jalbertSyncroTech** [comment] 2019-07-11 13:45
@SteveFarmerJr The doWork() entry point is called from a background thread, but the execution itself is synchronous - there's no way to eg. start some asynchronous operation, giving the doWork() thread back to the pool and then resume on a different background thread when the operation is complete.

It's not a show stopper, you can call .Wait() which blocks the doWork() thread, it just makes it more difficult to work with existing async/await or IObservable C# code.

**Comment by sdobart** [comment] 2019-07-11 15:41
While I have not tested that it actually works, I can confirm the bindings do exist for ListenableWorker, and I am able to inherit from it.

**Comment by toussam** [comment] 2019-08-23 09:41
@sdobart: Indeed, we can create a worker that will inherit from ListenableWorker, but @jalbertSyncroTech is correct, the startMethod is currently not available.

@moljac: Could you implement it? :)

**Comment by moljac** [comment] 2019-08-23 09:44
@toussam Open a new issue please!

> Could you implement it? 

Maybe implememntation is not necessary. Maybe the method was not surfaced for some reason.

And mention me. I did part of the bindings.

**Comment by toussam** [comment] 2019-08-23 13:30
Done! Thank you for your quick reply @moljac. ~

Wishing you a great weekend!

**Comment by sirkris** [comment] 2020-01-18 09:03
I found this thread on Google, trying to figure out what the namespace was for the "Worker" class because the docs (https://devblogs.microsoft.com/xamarin/getting-started-workmanager/) make no mention of it.  Turns out **the namespace we're looking for is AndroidX.Work**, in case anybody else came here looking for the same thing.

How is anybody supposed to know this if the documentation omits it?  A simple "using" statement at the top of your code examples would really go a long way in these cases.
