### ISSUE TITLE
AlertDialogs second view with action buttons is scrollable (25.1.0-beta2)

### ISSUE THREAD

**Issue by thebananazz** [xamarin/AndroidSupportComponents#34] opened 2017-01-10 07:53 UTC
### Xamarin.Android Version (eg: 6.0):
Xamarin.Android   7.0.2.42 (501e63c)

### Operating System & Version (eg: Mac OSX 10.11):
Android 6

### Support Libraries Version (eg: 23.3.0):
Xamarin Android Support Library - v4 25.1.0-beta2

### Describe your Issue:
AlertDialog has a scroll bar on the second view if the buttons are among each other.
![screenshot_20170110-084849](https://cloud.githubusercontent.com/assets/17413427/21797911/0e6e75be-d712-11e6-9c87-265fee8e2229.png)

### Steps to Reproduce (with link to sample solution if possible):
Use AlertDialog.Builder and fill the Dialog until it produces a scroll bar

### Include any relevant Exception Stack traces, build logs, adb logs:
-

**Comment by Redth** [comment] 2017-01-19 20:25
I'm guessing this will happen if you code the same thing in java too....

**Comment by thebananazz** [comment] 2017-01-19 20:40
Before I updated from 24.2.1 to this version I didn't have that problem.

That's the reason I thought it was a bug

**Comment by Redth** [comment] 2017-01-19 20:56
It's quite possibly a bug in the support libraries themselves :)  this sort of behaviour is most often not a bug in the binding layer.

Can you reproduce the same effect in a java app? or share the C# code you're using so I can try?

**Comment by thebananazz** [comment] 2017-01-30 07:35
`var builder = new AlertDialog.Builder(this._activity);
var view = this._activity.LayoutInflater.Inflate(Resource.Layout.TicketFilterDialog, null);
builder.SetView(view);

builder.SetTitle("Filter");
builder.SetPositiveButton("Suchen", (sender, args) =>
{
	//unimportant
});
builder.SetNeutralButton("Zurücksetzen", (sender, args) =>
{
	//unimportant
});

this.FilterDialog = builder.Show();`

**Comment by Redth** [comment] 2017-12-11 19:46
![image](https://user-images.githubusercontent.com/271950/33850479-0e001b96-de82-11e7-9809-f36af7bb174e.png)

Seems fixed with the latest support lib versions.

**Closed by Redth** 2017-12-11 19:46 UTC
Labels: need-info
